config/routes.rb
Rails.application.routes.draw do
  resources :maps do
    resources :ratings, only: [:create, :update]
    resources :map_files, only: [:create, :update, :destroy]
    resources :screenshots, only: [:create, :update, :destroy]
  end
  devise_for :users

  resources :users, only: [:show]

  root to: 'maps#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Map
    can :download, MapFile

    return unless user.present?
    by_me = {user: user}

    can :manage, Rating, by_me

    return unless user.mapper?

    can :create, Map
    can :update, Map, by_me
    can :manage, MapFile, { map: by_me }
    can :manage, Screenshot, { map: by_me }

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user
  has_many :ratings
  has_many :screenshots
  has_many :map_files

  mount_uploader :image, MapImageUploader

  def link_for(region)
    (self.links ||= {})[region.to_sym]
  end

  def link_for=(region, url)
    (self.links ||= {})[region.to_sym] = url
  end

  def has_links
    self.links && !self.links.empty?
  end

  validates :version do
    presence
    format with: /\Av?[1-9]\d*(\.\d+){0,2}\z/
    length maximum: 100
  end

  def gather_stats
    {
      community_pos: Rating.positive.of_community.count,
      community_neg: Rating.negative.of_community.count,
      mapper_pos: Rating.positive.of_mappers.count,
      mapper_neg: Rating.negative.of_mappers.count,
      pro_pos: Rating.positive.of_pros.count,
      pro_neg: Rating.negative.of_pros.count,
    }
  end
end

app/models/map_file.rb
class MapFile < ApplicationRecord
  belongs_to :map
  mount_uploader :file, MapFileUploader
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :map
  belongs_to :user

  scope :positive, -> { where(positive: true) }
  scope :negative, -> { where(positive: false) }

  scope :of_community, -> { where({}) }
  scope :of_mappers, -> { where({}) }
  scope :of_pros, -> { where({}) }
end

app/models/screenshot.rb
class Screenshot < ApplicationRecord
  belongs_to :map
  mount_uploader :image, MapImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :maps
  has_many :ratings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def admin?
    id == 1
  end

  def mapper?
    true
  end

  def pro?
    id == 3
  end

  def can_rate?(map)
    Rating.find_by(map: map, user: self).nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def resource_params # action_args + cancancan
    permitting_model_name = self.class.instance_variable_defined?(:@permitting_model_name) && self.class.instance_variable_get(:@permitting_model_name)
    model = (permitting_model_name || self.class.name.sub(/.+::/, '').sub(/Controller$/, '')).singularize.underscore.tr('/', '_').to_sym
    attrs = self.class.instance_variable_get(:@permitted_attributes)
    params.require(model).permit attrs
  end
end

app/controllers/map_files_controller.rb
class MapFileController < ApplicationController
  permits :name, :description, :file
  before_action :authenticate_user!, except: :download
  load_and_authorize_resource :map
  load_and_authorize_resource :map_file, through: :map

  def create
    @map_file.save
    redirect_to @map
  end

  def update(id, map_file)
    @map_file.update(map_file)
    redirect_to @map
  end

  def download
    send_file @map_file.file.current_path, filename: @map_file.name
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  permits :name, :description, :size, :mode, :category, :image
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /maps
  def index
    @total = Map.count
    if user_signed_in? && params[:only_unrated]
      @maps = @maps.where_not_exists(:ratings, {user: current_user})
    end
    @maps = @maps.page(params[:page])
  end

  # GET /maps/1
  def show
    @stats = @map.gather_stats

    if user_signed_in?
      @current_rating = Rating.find_by(user: current_user, map: @map)
    end
  end

  # GET /maps/new
  def new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  def create
    @map.user = current_user
    @map.latest = Time.now
    if @map.save
      redirect_to @map, notice: 'Map was successfully created.'
    else
      render :new
    end
  end

  # PUT /maps/1
  def update(id, map)
    @map.latest = Time.now
    if @map.update(map)
      redirect_to @map, notice: 'Map was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /maps/1
  def destroy(id)
    @map.destroy

    redirect_to maps_url, notice: 'Map was successfully destroyed.'
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  permits :positive, :comment
  before_action :authenticate_user!
  load_and_authorize_resource :map
  load_and_authorize_resource :rating, through: :map

  # TODO reply JS(?)
  # TODO authenticity

  def create
    @rating.save
    redirect_to @map
  end

  def update(id, rating)
    @rating.update(rating)
    redirect_to @map
  end
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  permits :name, :description, :image
  before_action :authenticate_user!
  load_and_authorize_resource :map
  load_and_authorize_resource :screenshot, through: :map

  def create
    @screenshot.save
    redirect_to @map
  end

  def update(id, screenshot)
    @screenshot.update(screenshot)
    redirect_to @map
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show(id)
    @user = User.find(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.haml
!!! html5
%html
  %head
    %meta(charset="utf-8")
    %title Mon Titre
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tag
    = csp_meta_tag
  %body
    .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-white.border-bottom.shadow-sm
      %h5.my-0.mr-md-auto.font-weight-normal PimpMyMaps
      %nav.my-2.my-md-0.mr-md-3
        %a.p-2.text-dark(href=root_path) List of maps
        //%a.p-2.text-dark(href="#") List of maps
        //%a.p-2.text-dark(href="#") List of maps
        //%a.p-2.text-dark(href="#") List of maps
      - if current_user.present?
        %a.btn.btn-outline-primary(href="#") Logged in as #{current_user.display_name}
        //%a.btn.btn-outline-primary(href="#") Logout
      - else
        %a.btn.btn-outline-primary(href=new_user_session_path) Log in
    = yield
    %footer.pt-4.my-md-5.pt-md-5.border-top
    = #javascript_include_tag "application"

app/views/map_files/_form.html.haml
= simple_form_for [map, file || MapFile.new] do |f|
  = f.input :name
  = f.input :description
  = f.input :file
  = f.submit 'Send'

app/views/map_files/_index.html.haml
- if can? :create, map => MapFile
  = render partial: 'map_files/form', locals: {map: map, file: MapFile.new}
- if files.size > 0
  %h5 This map has #{files.size} attached
  %ul
    - files.each do |file|
      %b= file.name
      // TODO :destroy

app/views/maps/_form.html.haml
= simple_form_for @map do |f|
  = f.error_notification

  = f.input :name
  = f.input :description, as: :text
  = f.input :size, collection: ['16x16', '32x32']
  = f.input :mode, collection: ['1v1', '2v2', '3v3', '4v4']
  = f.input :category, collection: ['Micro', 'Macro']
  = f.input :image, as: :file
  = f.submit 'Save'

app/views/maps/_regions.html.haml
- if map.has_links
  %ul
    - for region in %w(us kr na tw)
      - if map.link_for(region)
        %li= link_to map.link_for(region), region.upcase

app/views/maps/_stats.html.haml
%fieldset
  %legend Stats

  %b Positive for community
  = stats[:community_pos]
  %br
  %b Negative for community
  = stats[:community_neg]
  %br
  %b Positive for mapper
  = stats[:mapper_pos]
  %br
  %b Negative for mapper
  = stats[:mapper_neg]
  %br
  %b Positive for pro
  = stats[:pro_pos]
  %br
  %b Negative for pro
  = stats[:pro_neg]

app/views/maps/edit.html.haml
%h1 Editing map

= render 'form'

= link_to 'Show', @map
\|
= link_to 'Back', maps_path

app/views/maps/index.html.haml
.px-3.py-3.pt-md-5.pb-md-4.mx-auto.text-center
  %h3.display-4 List of Maps
  %p.lead
    - if user_signed_in? && params[:only_unrated]
      %span.badge.badge-secondary= @maps.size
      out of
    %span.badge.badge-secondary= @total
    maps in total

- if can? :create, Map
  %h5= link_to 'New Map', new_map_path

- if user_signed_in?
  - if params[:only_unrated]
    %h5 Only showing maps you haven't rated yet
    Click
    %b
      %a(href=root_path) here
    to only see all the maps!
  - else
    %h5 Showing all maps.
    Click
    %b
      %a{href: root_path(only_unrated: true)} here
    to only see maps you haven't rated yet!

= will_paginate @maps, params: params.slice(:only_unrated)

- @maps.each do |map|
  %span(style="float: left; /* XXX REMOVE THIS */")= map.thumbnail
  %h3.my-0= link_to map.name, map
  %small.text-muted= map.description
  -#.text-muted Size: #{map.size}
  -#.text-muted Mode: #{map.mode}
  -#.text-muted Last updated: #{map.latest}
  -#.text-muted Author: #{map.user.try(:name)}
  -#.text-muted Category: #{map.category}
  -#- if can? :manage, map
  -#  .text-muted= link_to 'Edit', map

app/views/maps/new.html.haml
%h1 New map

= render 'form'

= link_to 'Back', maps_path

app/views/maps/show.html.haml
%p#notice= notice

%h1= @map.name

- if @map.image?
  = @map.thumbnail

%p= @map.description

%b Author: #{@map.author_name}
%br
%b Latest version: #{@map.version}
%br
%b Size: #{@map.size}
%br
%b Mode: #{@map.mode}
%br
%b Category: #{@map.category}

= render partial: 'regions', locals: {map: @map}

= render partial: 'screenshots/index', locals: {map: @map, screenshots: @map.screenshots}

= render partial: 'map_files/index', locals: {map: @map, files: @map.map_files}

= render partial: 'stats', locals: {stats: @map.gather_stats}

- if @current_rating.present? ? can?(:update, @current_rating) : can?(:create, @map.ratings.build)
  = render partial: 'ratings/rate', locals: {map: @map, rating: @current_rating}
- else
  %h5 Log in to rate this map!

- if can? :update, @map
  = link_to 'Edit', edit_map_path(@map)
  \|
= link_to 'Back', maps_path

app/views/ratings/_form.html.haml
// since Ratings are "1 per map x user", always use "create"
// the controller will make do...
= simple_form_for([map, rating || Rating.new]) do |f|
  = f.input :positive
  = f.input :comment
  = f.submit "Save"

app/views/ratings/_rate.html.haml
- if rating.present?
  %h3 Your current rating: #{rating.positivity}
  %h5 Want to update your rating?
- else
  %h3 Rate this map!

= render partial: 'ratings/form', locals: {map: map, rating: rating}

app/views/screenshots/_form.html.haml
%h3 Add screenshot
= simple_form_for([map, screenshot]) do |f|
  = f.input :name
  = f.input :description
  = f.input :image
  = f.submit "Add"

app/views/screenshots/_index.html.haml
- if can? :create, @map => Screenshot
  = render partial: 'screenshots/form', locals: {map: map, screenshot: Screenshot.new}
- if screenshots.size > 0
  %h5 This map has #{screenshots.size} screenshot(s) attached
  - screenshots.each do |screenshot|
    = screenshot.thumbnail
    // TODO :destroy

app/views/users/show.html.haml
%h1= @user.display_name

- if @user.maps.size > 0
  %b Released maps: #{@user.maps.size}
  %ul
    - @user.maps.each do |map|
      %li
        = map.thumbnail
        %h3= link_to map.name, map